### ISSUE TITLE
Variable expansion doesn't work on `include`

### ISSUE THREAD

**Issue by lontivero** [CDSoft/panda#10]
I'm using `panda` as part of my wiki site generator and i need the paths to be relative to the wiki root directory. I wanted to solve it by doing:

<pre>
```meta
wroot = "/home/user/Documents/Wiki/src/wasabi"
```

:::{include={{wroot}}/radical_ideas.md}}
whatever
:::

</pre>

But it doesn't include the file. Instead it results in:

![image](https://user-images.githubusercontent.com/127973/190917173-c6ecaa00-5b70-4ee1-92ea-62aa7f2a6c11.png)

However, if I hardcode the file path it works like charm.

**Comment by lontivero** [comment]
Sorry for the spam. It works, i just needed to escape the variable pattern as follow:

<pre>
:::{include=\{\{wroot\}\}/radical_ideas.md}
whatever
:::
</pre>

**Comment by CDSoft** [comment]
Hello,
You can make it easier to read with quotes:

``` markdown
::: { include="{{wroot}}/radical_ideas.md" }
whatever
:::
```

BTW your first example also had two brackets at the end of the line.
