### ISSUE TITLE
gnuplot diagrams are not rendered

### ISSUE THREAD

**Issue by lontivero** [CDSoft/panda#12]
While `graphviz` diagrams work well, `gnuplot` doesn't. I've tried with all possible ideas but nothing seems to work. This example is taken from the doc (with `img` and `out` modified). I have `gnuplot` installed 

<pre>
```{render="gnuplot -e 'set terminal svg' -e 'set output "%o.svg"' -c %i"
     img="../../src/images/panda_gnuplot_example"
     out="/home/lontivero/Documents/Wiki/src/images" }
set xrange [-pi:pi]
set yrange [-1.5:1.5]
plot sin(x) lw 4, cos(x) lw 4
```
</pre>

This is the result (pandoc rendered html output): 
![image](https://user-images.githubusercontent.com/127973/191158838-84c7f673-b180-41b2-b44e-cf16cb95592a.png)

I don't know how to debug nor how to get more info to help understand what can be going wrong. Any idea?

**Comment by CDSoft** [comment]
This is a bug in the documentation. The inner quotes in the `render` attribute shall be escaped:

    ```{render="gnuplot -e 'set terminal svg' -e 'set output \"%o.svg\"' -c %i"
         img="../../src/images/panda_gnuplot_example"
         out="/home/lontivero/Documents/Wiki/src/images" }
    set xrange [-pi:pi]
    set yrange [-1.5:1.5]
    plot sin(x) lw 4, cos(x) lw 4
    ```

You can also use predefined variables for some diagrams:

    ```{render="{{gnuplot}}"
         img="../../src/images/panda_gnuplot_example"
         out="/home/lontivero/Documents/Wiki/src/images" }
    set xrange [-pi:pi]
    set yrange [-1.5:1.5]
    plot sin(x) lw 4, cos(x) lw 4
    ```

**Comment by lontivero** [comment]
Works! Thank you.
