### ISSUE TITLE
error when reading boolean metadata

### ISSUE THREAD

**Issue by kbro237** [CDSoft/panda#2]
I'm getting an error whenever I have a boolean value in my metadata, for example `link-citations: true`

I believe the error is coming from the `read_vars_in_meta` function, when it tries to unpack the table.

**Comment by CDSoft** [comment]
Hello.
Thank you for your patch.
I tried to add some tests and booleans can not simply be stored as booleans (`{{link-citations}}` will crash Pandoc).
I will propose a slightly different solution where non table values are converted to strings.
