### ISSUE TITLE
Highlight code block

### ISSUE THREAD

**Issue by Jab2870** [CDSoft/panda#9]
It is sometimes useful to highlight a line or section of code inside a code block in order to bring attention to it. Is this something that panda would consider implementing?

For example

````
```{highlight=2-3}
line1
line2
line3
```
````

might result in lines 2 and 3 being hilighted

**Comment by CDSoft** [comment]
Hello,

Thanks for the suggestion.

I currently have very few time for panda but I may consider porting https://owickstrom.github.io/pandoc-emphasize-code/

**Comment by Jab2870** [comment]
That is exactly what I was looking for, thanks very much
